"use server";
import { del,put } from "@vercel/blob"; import { revalidatePath } from "next/cache"; import { redirect } from "next/navigation"; import { requireAdmin } from "@/lib/admin"; import { getSql } from "@/lib/db"; import { defaultAppearance,defaultSpecialties,getContent } from "@/lib/content";
const value=(fd:FormData,key:string,fallback="")=>{const v=fd.get(key);return typeof v==="string"?v.trim():fallback;};
const head=(fd:FormData)=>({eyebrow:value(fd,"eyebrow"),title:value(fd,"title"),accent:value(fd,"accent"),description:value(fd,"description")});
const pairs=(fd:FormData,count:number,a:string,b:string)=>Array.from({length:count},(_,i)=>({[a]:value(fd,`${a}_${i}`),[b]:value(fd,`${b}_${i}`)}));
async function saveSection(key:string,data:unknown,publicPath:string,adminPath:string){await requireAdmin(adminPath);const sql=await getSql();const json=JSON.stringify(data);await sql`INSERT INTO site_content (content_key,content_json,updated_at) VALUES (${key},${json},NOW()) ON CONFLICT (content_key) DO UPDATE SET content_json=EXCLUDED.content_json,updated_at=NOW()`;revalidatePath(publicPath);revalidatePath("/");redirect(`${adminPath}?saved=1`);}
export async function saveProfile(fd:FormData){await requireAdmin("/admin/perfil");const sql=await getSql();const current=await sql`SELECT profile_image_url FROM artist_profile WHERE id=1`;const oldUrl=(current[0] as {profile_image_url?:string}|undefined)?.profile_image_url||null;const photo=fd.get("photo");let imageUrl:string|null=null;if(photo instanceof File&&photo.size>0){if(!photo.type.startsWith("image/")||photo.size>8_000_000)throw new Error("Envie uma imagem de até 8 MB.");const blob=await put(`perfil/${photo.name}`,photo,{access:"public",addRandomSuffix:true});imageUrl=blob.url;}
const name=value(fd,"name","André Ribeiro"),headline=value(fd,"headline"),bio=value(fd,"bio"),city=value(fd,"city"),whatsapp=value(fd,"whatsapp").replace(/\D/g,""),instagram=value(fd,"instagram").replace(/^@/,""),years=value(fd,"yearsExperience","+20");
await sql`INSERT INTO artist_profile (id,name,headline,bio,city,whatsapp,instagram,years_experience,profile_image_url,updated_at) VALUES (1,${name},${headline},${bio},${city},${whatsapp},${instagram},${years},${imageUrl},NOW()) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,headline=EXCLUDED.headline,bio=EXCLUDED.bio,city=EXCLUDED.city,whatsapp=EXCLUDED.whatsapp,instagram=EXCLUDED.instagram,years_experience=EXCLUDED.years_experience,profile_image_url=COALESCE(EXCLUDED.profile_image_url,artist_profile.profile_image_url),updated_at=NOW()`;
if(imageUrl&&oldUrl){try{await del(oldUrl);}catch{}}revalidatePath("/");revalidatePath("/perfil");revalidatePath("/artes");redirect("/admin/perfil?saved=1");}
export async function saveHome(fd:FormData){return saveSection("home",{...head(fd),strip:[0,1,2,3].map(i=>value(fd,`strip_${i}`)),exploreEyebrow:value(fd,"exploreEyebrow"),exploreTitle:value(fd,"exploreTitle"),exploreDescription:value(fd,"exploreDescription"),cards:Array.from({length:6},(_,i)=>({title:value(fd,`cardTitle_${i}`),text:value(fd,`cardText_${i}`)}))},"/","/admin/configuracoes");}
export async function saveAppearance(fd:FormData){await requireAdmin("/admin/aparencia");const current=await getContent("appearance",defaultAppearance);const file=fd.get("heroImage");let heroImageUrl=current.heroImageUrl;if(file instanceof File&&file.size>0){if(!file.type.startsWith("image/")||file.size>12_000_000)throw new Error("Envie uma imagem de até 12 MB.");const blob=await put(`aparencia/capa-${file.name}`,file,{access:"public",addRandomSuffix:true});heroImageUrl=blob.url;if(current.heroImageUrl){try{await del(current.heroImageUrl);}catch{}}}const hex=(key:string,fallback:string)=>/^#[0-9a-fA-F]{6}$/.test(value(fd,key))?value(fd,key):fallback;return saveSection("appearance",{logoInitials:value(fd,"logoInitials","AR").slice(0,3).toUpperCase(),brandSuffix:value(fd,"brandSuffix","Tattoo"),goldColor:hex("goldColor",defaultAppearance.goldColor),goldBrightColor:hex("goldBrightColor",defaultAppearance.goldBrightColor),backgroundColor:hex("backgroundColor",defaultAppearance.backgroundColor),heroImageUrl,heroPosition:value(fd,"heroPosition","center center"),heroOverlay:value(fd,"heroOverlay","78"),siteTitle:value(fd,"siteTitle",defaultAppearance.siteTitle),siteDescription:value(fd,"siteDescription",defaultAppearance.siteDescription)},"/","/admin/aparencia");}
export async function saveSpecialties(fd:FormData){await requireAdmin("/admin/especialidades");const current=await getContent("specialties",defaultSpecialties);const items=[];for(let i=0;i<4;i++){const file=fd.get(`image_${i}`);let imageUrl=current.items[i]?.imageUrl||"";if(file instanceof File&&file.size>0){if(!file.type.startsWith("image/")||file.size>8_000_000)throw new Error("Cada imagem deve ter no máximo 8 MB.");const blob=await put(`especialidades/${i}-${file.name}`,file,{access:"public",addRandomSuffix:true});if(imageUrl){try{await del(imageUrl);}catch{}}imageUrl=blob.url;}items.push({title:value(fd,`title_${i}`),text:value(fd,`text_${i}`),example:value(fd,`example_${i}`),position:value(fd,`position_${i}`),imageUrl});}return saveSection("specialties",{...head(fd),items},"/especialidades","/admin/especialidades");}
export async function saveProcess(fd:FormData){return saveSection("process",{...head(fd),items:pairs(fd,4,"title","text")},"/atendimento","/admin/atendimento");}
export async function saveCare(fd:FormData){return saveSection("care",{...head(fd),note:value(fd,"note"),items:pairs(fd,6,"title","text")},"/cuidados","/admin/cuidados");}
export async function saveTestimonials(fd:FormData){return saveSection("testimonials",{...head(fd),items:Array.from({length:3},(_,i)=>({quote:value(fd,`quote_${i}`),name:value(fd,`name_${i}`),style:value(fd,`style_${i}`)}))},"/depoimentos","/admin/depoimentos");}
export async function saveFaq(fd:FormData){return saveSection("faq",{...head(fd),items:Array.from({length:6},(_,i)=>({question:value(fd,`question_${i}`),answer:value(fd,`answer_${i}`)}))},"/duvidas","/admin/duvidas");}
export async function savePortfolio(fd:FormData){return saveSection("portfolio",{eyebrow:value(fd,"eyebrow"),title:value(fd,"title"),description:value(fd,"description")},"/artes","/admin/instagram");}
export async function saveQuotePage(fd:FormData){return saveSection("quote",{...head(fd),responseTitle:value(fd,"responseTitle"),responseText:value(fd,"responseText")},"/orcamento","/admin/orcamento");}
export async function updateQuoteStatus(fd:FormData){await requireAdmin("/admin/orcamentos");const id=Number(value(fd,"id")),status=value(fd,"status","novo");if(!id||!["novo","respondido","arquivado"].includes(status))throw new Error("Status inválido.");const sql=await getSql();await sql`UPDATE quote_request SET status=${status} WHERE id=${id}`;revalidatePath("/admin/orcamentos");redirect("/admin/orcamentos?saved=1");}
