import { getSql } from "@/lib/db";

export type ArtistProfile={name:string;headline:string;bio:string;city:string;whatsapp:string;instagram:string;yearsExperience:string;profileImageUrl:string|null};
export const defaultProfile:ArtistProfile={name:"André Ribeiro",headline:"Realismo que transforma histórias em arte.",bio:"Tatuador há mais de 20 anos, André Ribeiro é especialista em realismo, Black & Grey, animais e arte religiosa. Cada projeto nasce de uma conversa e é desenhado para respeitar a história, a anatomia e a identidade de quem o carrega.",city:"Cachoeirinha · RS",whatsapp:"5551992643880",instagram:"andreribeirotattoo",yearsExperience:"+20",profileImageUrl:null};
export async function getProfile():Promise<ArtistProfile>{try{const sql=await getSql();const rows=await sql`SELECT name,headline,bio,city,whatsapp,instagram,years_experience,profile_image_url FROM artist_profile WHERE id=1`;const row=rows[0] as Record<string,string|null>|undefined;if(!row)return defaultProfile;return{name:row.name||defaultProfile.name,headline:row.headline||defaultProfile.headline,bio:row.bio||defaultProfile.bio,city:row.city||defaultProfile.city,whatsapp:row.whatsapp||defaultProfile.whatsapp,instagram:row.instagram||defaultProfile.instagram,yearsExperience:row.years_experience||defaultProfile.yearsExperience,profileImageUrl:row.profile_image_url||null};}catch{return defaultProfile;}}
export type InstagramItem={id:string;caption?:string;media_type:"IMAGE"|"CAROUSEL_ALBUM"|"VIDEO";media_url?:string;thumbnail_url?:string;permalink:string;timestamp:string};
export async function getInstagramItems():Promise<InstagramItem[]>{const token=process.env.INSTAGRAM_ACCESS_TOKEN;if(!token)return[];try{const url=new URL("https://graph.instagram.com/me/media");url.searchParams.set("fields","id,caption,media_type,media_url,permalink,thumbnail_url,timestamp");url.searchParams.set("access_token",token);url.searchParams.set("limit","24");const response=await fetch(url,{next:{revalidate:900}});if(!response.ok)return[];const result=await response.json() as {data?:InstagramItem[]};return result.data||[];}catch{return[];}}
export type QuoteRequest={id:number;name:string;phone:string;body_area:string;approximate_size:string|null;style:string|null;idea:string;status:string;created_at:string};
export async function getQuoteRequests():Promise<QuoteRequest[]>{try{const sql=await getSql();return await sql`SELECT id,name,phone,body_area,approximate_size,style,idea,status,created_at FROM quote_request ORDER BY id DESC LIMIT 50` as QuoteRequest[];}catch{return[];}}
export type TestimonialRequest={id:number;name:string;city:string|null;tattoo_style:string|null;message:string;status:"pendente"|"aprovado"|"oculto";created_at:string};
export async function getApprovedTestimonials():Promise<TestimonialRequest[]>{try{const sql=await getSql();return await sql`SELECT id,name,city,tattoo_style,message,status,created_at FROM testimonial_request WHERE status='aprovado' ORDER BY reviewed_at DESC NULLS LAST,id DESC LIMIT 30` as TestimonialRequest[];}catch{return[];}}
export async function getTestimonialRequests():Promise<TestimonialRequest[]>{try{const sql=await getSql();return await sql`SELECT id,name,city,tattoo_style,message,status,created_at FROM testimonial_request ORDER BY CASE WHEN status='pendente' THEN 0 WHEN status='aprovado' THEN 1 ELSE 2 END,id DESC LIMIT 100` as TestimonialRequest[];}catch{return[];}}
